[package]
name = "codex-memory"
version = "0.0.0"
edition = "2024"

[lib]
name = "codex_memory"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = "1"
fs2 = "0.4"

[dev-dependencies]
tempfile = "3"

