# Capability levels and allowlists for sandboxed execution
# These profiles integrate with existing --sandbox and approval policies.

level: READ_ONLY

allowed_commands:
  READ_ONLY:
    - /usr/bin/rg
    - /usr/bin/git
    - /usr/bin/cat
    - /usr/bin/node
    - /usr/bin/python3
  WORKSPACE_WRITE:
    - inherit: READ_ONLY
    - /usr/bin/npm
    - /usr/bin/pnpm
    - /usr/bin/cargo
  SYSTEM_WRITE:
    - inherit: WORKSPACE_WRITE
    - /usr/bin/uv
    - /usr/bin/apt-get
  GODMODE:
    - inherit: SYSTEM_WRITE

allowed_hosts:
  READ_ONLY: []
  WORKSPACE_WRITE:
    - github.com
    - pypi.org
    - registry.npmjs.org
  SYSTEM_WRITE:
    - inherit: WORKSPACE_WRITE
  GODMODE:
    - "*"

logging:
  # Relative to repo by default; CI may relocate to ~/.coder/audit/
  policy_log: logs/policy.jsonl

# Optional defaults control:
# When disable_builtin_allowlists is true, Codex will not apply its built‑in
# allowlists for commands/hosts when your policy does not specify entries for a
# level. This makes the policy file fully authoritative. Note: GODMODE always
# retains its built‑in host defaults for safety telemetry; this knob is ignored
# for GODMODE.
#
#defaults:
#  disable_builtin_allowlists: true

# GODMODE options (take effect only when profile is danger‑full‑access):
# - allow_host_fallback: when true, if no isolation wrapper script is present,
#   execution may fall back to host with a prominent warning and audit log.
# - wall_time_secs: optional per‑session budget for high‑privilege execs.
#
#godmode:
#  allow_host_fallback: false
#  wall_time_secs: 900
